import re
import xlwt
import os
from tkinter import filedialog
from tkinter import *
from tkinter import messagebox


"""
Define function for numerical data extraction from the input file .dat
"""

def function(inputFile):

   """Data - list that contains all the forces/moments data in string format"""

   data = []

   """Open input file and read every line, extract data when line begins with Totals"""
    
   with open(inputFile, 'r') as f:
        for line in f:
            if line.startswith('Totals'):
                data.append(line)

   lenCases = len(data)
     
   """Extract numbers from Totals line in string format"""
	
   n = 0
   for i in data:
        a = i.split(',')
        data[n] = a[4:]
        n += 1
		
   """ Convert numbers from string format to float"""

   for totals in data:
        for number in range(6):
            totals[number] = float(totals[number])

   """Append numbers to values list (here you can insert a specific order if you want)"""

   values = []
   values.append(["Fx", "Fy", "Fz", "Mx", "My", "Mz"])

   for n in range(lenCases):
        values.append(data[n])
   return (values, lenCases)


"""
Define function for load case name extraction from the input file .dat
"""

def function2(inputFile):

    loadcases = ['Load Case']

    with open(inputFile, 'r') as f:
        for lines in f:
            if lines.startswith('"Freebody Loads"'):
                entries = re.split(" ", lines, 18)
                loadcases.append(entries[6][:-1])
    return (loadcases)

"""
Main Program execution function
"""

def runExtraction():

    """ Create output Excel file"""
	
    wb = xlwt.Workbook()
	
    global lst
    for filename in lst:
        date, lenCases = function(filename)
        loadcases = function2(filename)
        head, tail = os.path.split(filename)
        ws = wb.add_sheet(tail)
        for i in range(lenCases+1):
            for j in range(7):
                if j == 0:
                    ws.write(i, j, loadcases[i])
                else:
                    ws.write(i, j, date[i][j-1])
    wb.save('Results.xls')
    messagebox.showinfo('Status', 'Execution Successful')

"""
TKINTER Module for GUI implementation
"""

def browseFunction():
    global lst
    filez =  filedialog.askopenfilenames(initialdir = "/",title = "Select file",filetypes = (("dat files","*.dat"),("all files","*.*")))
    lst=list(filez)
    return (lst)

master = Tk()
master.wm_title("FLEX - Freebody Loads Extractor")
lst = []
	
"""
Create buttons and text for GUI 
"""

T = Text(master, height=10, width=60)
T.pack()
T.insert(END, "This is a script for extracting forces and moments "
         "from the\nFreebody Load .dat file generated by Patran.\n\n"
         "Step.1. Browse for the .dat files and select all of them\n"
         "Step.2. Run the program\n"
         "Step.3. A Results.xls file will be created with the totals\n"
         "output for each Load Case in a separate worksheet\n\n"
        "Note: Name of the .dat file should not exceed 27 characters")
b = Button(master, text="Browse file", bg='red', width=10, height=2, bd=3, command=browseFunction)
b.pack(side=LEFT)
c = Button(master, text="Run", bg='green', width=10, height=2, bd=3, command=runExtraction)
c.pack(side=LEFT)

master.mainloop()
